
[build]
publish = "dist"
command = """
git fetch --tags && git switch --detach FETCH_HEAD && git tag --list && curl -fsSL https://deno.land/install.sh | sh && PATH=$PATH:/opt/buildhome/.deno/bin/ deno task prod
"""
