# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task prod
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: |
          echo "new_version=$(echo '${{env.GITHUB_REF_NAME}}' | cut -c 2-)" >> $GITHUB_ENV
      - run: npm version --git-tag-version=false ${{env.new_version}}
      - run: git add package.json package-lock.json
      - run: git commit -m "bump npm version to v${{env.new_version}}"
      - run: git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
