# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.base_ref}}
      - name: exit if not production
        if: endsWith(github.event.base_ref, 'prod') == false
        run: exit -1
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task prod
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          npm version --git-tag-version=false $(echo '${{github.ref_name}}' | cut -c 2-)
          git commit -a -m "bump npm version to v$(echo '${{github.ref_name}}' | cut -c 2-)"
          git push origin HEAD:prod
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
